# Generated by Django 2.2.19 on 2022-07-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('index', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('publish', models.CharField(default=None, max_length=50)),
                ('age', models.CharField(max_length=5)),
                ('year', models.CharField(max_length=5)),
                ('pages', models.IntegerField()),
                ('rating', models.FloatField()),
                ('cove', models.TextField()),
                ('description', models.TextField()),
                ('slug', models.SlugField(default=True, unique=True)),
            ],
        ),
    ]
