# Generated by Django 2.2.19 on 2022-07-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='books_book',
            new_name='Book',
        ),
    ]
