# Generated by Django 2.2.16 on 2022-11-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='name_lower',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
