# Generated by Django 2.2.19 on 2022-07-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20220722_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='index',
            field=models.IntegerField(default=None),
        ),
    ]
