# Generated by Django 2.2.19 on 2022-12-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
