# Generated by Django 2.2.19 on 2022-08-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20220730_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='books/', verbose_name='Картинка'),
        ),
    ]
