# Generated by Django 2.2.19 on 2022-08-21 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_author_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='image',
            new_name='photo',
        ),
    ]
