# Generated by Django 2.2.19 on 2022-12-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20221206_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='tags',
        ),
    ]
