# Generated by Django 2.2.19 on 2022-12-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='vector',
            field=models.TextField(blank=True, null=True),
        ),
    ]
