# Generated by Django 2.2.19 on 2022-08-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_remove_author_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
