# Generated by Django 2.2.19 on 2022-08-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cove',
            field=models.TextField(blank=True, null=True),
        ),
    ]
