# Generated by Django 2.2.19 on 2022-10-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20220825_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_favore',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
