# Generated by Django 3.2.18 on 2023-05-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20230507_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='shop',
            field=models.TextField(blank=True, null=True),
        ),
    ]
