# Generated by Django 2.2.19 on 2022-10-26 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0014_book_is_favore'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoreBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('person', models.ForeignKey(blank=True, help_text='Ссылка пользователя, который поставил like', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, который поставил like')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='favorites',
            field=models.ManyToManyField(through='books.FavoreBook', to=settings.AUTH_USER_MODEL),
        ),
    ]
